### ISSUE TITLE
Do you have any examples showing how to use "vpk upload az"

### ISSUE THREAD

**Issue by aherrick** [velopack/velopack#194]
wanted to say I was able to get converted over to VELO very easily and love the way it works! sharing my current GH actions pipeline here hopefully it helps others.

```
    - name: dotnet publish 
      #https://github.com/velopack/velopack/issues/96
      run: dotnet publish .\MyApp\MyApp.csproj -r win-x64 -f net8.0 -c Release -o .\MyApp\publish --self-contained

    - name: velopack install
      run: dotnet tool update -g vpk

    - name: velopack pack
      run: vpk pack -u MyApp -v 1.0.${{ github.run_number }} -p .\MyApp\publish -e MyApp.exe --packTitle "MyApp" --outputDir .\MyApp\release

    - name: release
      uses: LanceMcCarthy/Action-AzureBlobUpload@v2
      with:
        connection_string: ''
        container_name: mycontainername
        source_folder: .\MyApp\release
        clean_destination_folder: true
        is_recursive: false
        delete_if_exists: true     
```     

I'm using `LanceMcCarthy/Action-AzureBlobUpload@v2` which works great, but wouldn't mind using `vpk upload az ` if I knew how to pass connection string/container/source folder to it. 

thank you for all your work!
